PROJECT_PATHS=(
$HOME/Projects/Projekty-linux/moje
$HOME/Projects/Projekty-linux/ansible
$HOME/Projects/Projekty-linux/forki
$HOME/Projects/Projekty-linux/inne
$HOME/AUR/all
$HOME/AUR/new
$HOME/AUR/broken
)
